phpdoc:
  build: .

phpunit:
  build: docker/with-xdebug
  volumes: [".:/opt/phpdoc"]
  working_dir: "/opt/phpdoc"
  command: ["./tools/phpunit"]

behat:
  build: docker/with-xdebug
  volumes: [".:/opt/phpdoc"]
  working_dir: "/opt/phpdoc"
  command: ["./bin/behat"]

phpcs:
  build: docker/with-xdebug
  volumes: [".:/opt/phpdoc"]
  working_dir: "/opt/phpdoc"
  command: ["./bin/phpcs", "--standard=PSR2", "--extensions=php",  "src"]

phpstan:
  image: jaapio/github-actions:phpstan
  environment:
    PHP_EXTENSIONS: php7-intl php7-xsl
  volumes: [".:/app"]
  command: "analyse src tests --level 4 --configuration phpstan.neon"
